version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://unicorehomedb:3306/basics?allowPublicKeyRetrieval=true
    depends_on:
      - unicorehomedb
    
    volumes:
      - .m2:/root/.m2
      
  unicorehomedb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net  
    environment:
      MYSQL_DATABASE: basics
      MYSQL_USER: amila_one
      MYSQL_PASSWORD: Amila_pw
      MYSQL_ROOT_PASSWORD: Amila_Rpw
networks:
  springapimysql-net:
